### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by jamiesonbecker** [userify/shim#16]
@purinda at News Corp added support for environment proxy variables:

https://github.com/news-life-media/shim/blob/master/shim.py#L124

**Comment by purinda** [comment]
@jamiesonbecker any updates on getting this merged? I know this affects the core functionality, so let me know if you or someone else need help testing this further.

**Comment by jamiesonbecker** [comment]
Excellent point, sorry for the delay! Please test and make sure this works!

**Comment by purinda** [comment]
Thanks for adding the Proxy support @jamiesonbecker I will test this first thing tomorrow and get back to you, so we can close this issue. Cheers!

**Comment by jamiesonbecker** [comment]
Excellent! Just made another minor change to support http[s]:// in https_proxy

**Comment by jamiesonbecker** [comment]
Merged https://github.com/userify/shim/commit/78ede8e4198dd31fb4a8c7499107f2ead3c59465

**Comment by jamiesonbecker** [comment]
@purinda pls feel free to close this if it's working ok :)

**Comment by purinda** [comment]
@jamiesonbecker can't close it, may be permissions. I can confirm this is working.

**Comment by jamiesonbecker** [comment]
Ah ok great! Closing now. Thank you again!
