### ISSUE TITLE
CoreOS support

### ISSUE THREAD

**Issue by jamiesonbecker** [userify/shim#18]
CoreOS has no Python and needs to have libraries installed.

We don't have a statically compiled shim yet, but it's under development. In the interim, testing with a dynamically linked shim:

core@ip-172-31-14-236 ~/shim-static-compile $ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/core/shim-static-compile/libpython2.7.so.1.0 ./shim
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site

In order to support this use case (and other extremely minimal distributions without Python, such as IoT), it probably makes sense to statically compile Python and link as much as possible of the stdlib.

An alternative approach, such as userifier (https://github.com/ess/userifier), is a minimal version of the shim in Golang. Both of these languages produce large binaries.

A third approach will be for us to provide a minimal API resource that provides newline-delimited users in a strictly correct, pre-sanitized version (i.e., whitelisted characters, C POSIX locale, etc) and write a minimal bash version. This would mean a very fast startup as well, but less capabilities down the road. For lightweight containers, this approach is probably optimal.

Community feedback gratefully accepted.

**Comment by jamiesonbecker** [comment]
Perhaps a second, minimal POSIX sh (or bash) agent, requiring only curl or wget (either) and perhaps bc. This would be ideal to support additional non-Linux platforms (esp including OSX, Solaris, FreeBSD) and would result in much faster startup, but without the extensibility or crash safety of the Python shim.

**Comment by ess** [comment]
Not that this is a good basis for comparison, but I do recall Gentoo having Bash4 as the default as far back as 2009 or so.

I'd say that you'd also be hard-pressed to find a minimal distro that doesn't have at least one of either wget or curl, but chances are that my having said that means that somebody's rolling one right this minute.

**Comment by jamiesonbecker** [comment]
Agreed completely. (but of course gentoo is fast about everything). Bash4 I think was only released in 2009 or so. Old versions of big iron unix didn't even have bash back in the day (those were really bad days). Agreed to wget and curl too -- if you don't have one of those, you're probably not going to have nc either (unless you're black hatting that day!)

Ok. I'm guessing bash4 but sed/awk/etc should be available and posix sh isn't that bad.. math might be hard without bash4 or bc (figuring out seconds elapsed etc), but a basic shim should be possible with just hard-coded times.

So, only dependencies might be..
/bin/sh
wget | curl
sed
useradd/userdel/sudo

I don't really want to remove the dependency on /etc/sudoers.d, since it really makes managing sudoers much cleaner and safer. If you've got sudo, you've probably got a new enough configuration w/ include.

**Comment by jceloria** [comment]
Not that it matters much with having homebrew available but MacOSX is still shipping Bash3:
-(~)$-> /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.

Calculating times isn't an issue with GNU date using epoch differences but then again, I don't really know what you are doing? 

As far as sudoers.d I know that RHEL/CentOS5 doesn't support it out of the box, but you can include the directory and it will then work.

/dev/tcp existed since bash 2.04 so if you really wanted to go minimalist you could use that and not have to worry about the curl/wget dependancy ;) 
http://superuser.com/questions/40545/upgrading-and-installing-packages-through-the-cygwin-command-line/496572#496572

**Comment by jamiesonbecker** [comment]
> Calculating times isn't an issue with GNU date
just simple subtraction like (pseudocode) sleep $(10-.2)

> As far as sudoers.d I know that RHEL/CentOS5 doesn't support it out of the box, but you can include the directory and it will then work.
Sounds reasonable - maybe a grep and echo >> for /etc/sudoers.conf?

> /dev/tcp
wow, that's awesome. great idea -- /dev/tcp avail in *bsd? Currently, the shim POST's data so it can provide additional data back up (coming soon) in POST body, but for this minimal shim, a simple get's should do the trick just fine and make that easier.

**Comment by jceloria** [comment]
/dev/tcp is platform independent... Its pure bash.

And yeah something along the lines of:
# grep -Eq '^include sudoers.d' /etc/sudoers.conf || echo 'include
sudoers.d' >> /etc/sudoers.conf

Ought to solve that problem.

**Comment by jceloria** [comment]
I'm on my phone and it keeps crashing while typing email!!!!

I'm not sure when sudo added support for sudoers.d so it may be worth
looking into for other platforms as well

**Comment by jceloria** [comment]
https://gist.github.com/Sitwon/8244641

**Comment by jceloria** [comment]
I can help test that later in bash3 on my Mac when I get in front of it.

**Comment by jamiesonbecker** [comment]
Sounds perfect! I'll start on the API with newline-delimited output over the weekend.

**Comment by jamiesonbecker** [comment]
Could use cut or awk to scrape /etc/passwd (https://github.com/userify/shim/blob/master/shim.py#L222). The API could pre-base64 the authorization string (https://github.com/userify/shim/blob/master/shim.py#L211) during install so that binary could be eliminated for the /dev/tcp idea. Timeouts and failures could be handled in subshells.

I wonder what the relative availability of these utils are. Probably cut and awk are available almost everywhere. Also thinking about what busybox has in it (for minimal IoT boxes, containers, etc) or super light-weight distros or distros (usually built on busybox) like Alpine Linux (formerly Damn Small Linux) and CoreOS.

The biggest remaining question is cross-platform startup going back for several generations of Userify, since half the UNIX/Linux community is tossing out SysV and the *bsd's always preferred other options. Is /etc/rc.local (where available) the common thread? /etc/init.d? (some init systems -- not naming names -- seem to want to force you to source their daemon control libraries or they won't work).

**Comment by jceloria** [comment]
Scrape passwd for what?

Why must you have "cross-platform startup"? Whats wrong with looking at the
platform you're on and then checking the available options for said
platform and the providing the necessary startup script? If you want single
inflexible rigid shit maintained by a totalitarian corporation then perhaps
you should start writing msi's or exe's... I also hear apple is quite rigid
in what it allows, you can use xcode and cocoa and not have to be bothered!

**Comment by jceloria** [comment]
I'm sorry... I just read that back and it seemed rude, I didn't intend for
it to be.

**Comment by jamiesonbecker** [comment]
This is temporarily on hold unless someone wants to take over on it..

**Comment by jamiesonbecker** [comment]
Closing this issue for now.

Some users have developed CoreOS versions of the agent and we are working with them to make them available; please contact support@userify.com if this is important to you!
