### ISSUE TITLE
Shim Version 2 Brainstorm

### ISSUE THREAD

**Issue by jamiesonbecker** [userify/shim#20]
Holding place for a wishlist for the next version of the shim.

things to hold onto..
0. no local dependencies except for things that are usually built-in (i.e., curl, bash, python)
1. instant installation and deployment
2. bullet-proof. If anything fails, just try again. above all, updates should never corrupt working install.
3. works almost everywhere (see 1)
4. simplicity, readable code, and modifiable source
5. server upgradeability

**Comment by pnomolos** [comment]
Not sure if this should go here or elsewhere, but a built-in to reconfigure the credentials would be fantastic.  Using my workflow as an example, it would allow for the base images built by packer to include userify, and terraform could re-configure as necessary.  This would make build an image that's shared between staging and production even simpler.

**Comment by jamiesonbecker** [comment]
If I'm following your use case, *boom* done! :)

The move server script will rewrite the credentials for you. But this seems like a really common use case, so we should definitely call that out a lot more!

**Comment by jamiesonbecker** [comment]
Shim version 2.0 is on the way. It will probably not replace shim 1 for a while, but it will be available to environments that don't have a built-in Python. Email beta@userify.com with requests or if you need details.
