### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by nelaaro** [userify/shim#25]
We are having the following issues when running shim on

I will submit a pull request soon. With my fix. 
I am only running a CentoOS 6 environment and have only tested in a CentoOS environment. 
This is related to the following issue http://lwn.net/Articles/682553/
cat /etc/issue
CentOS release 6.7 (Final)

On the initial install 

>  curl -v -sS "https://static.userify.com/installer.sh" |     api_key="jNNGyRNkeLVL2TFjJs8FucD5CoAAX8284EFmrLM2RgYgwcaxR6"     api_id="4vDX5uRZXdZM887CEWXgQc_user"     static_host="static.userify.com"     shim_host="configure.userify.com"     self_signed=0     sudo -sE
>  * About to connect() to static.userify.com port 443 (#0)
>  *   Trying 104.20.15.168... connected
>  * Connected to static.userify.com (104.20.15.168) port 443 (#0)
>  * Initializing NSS with certpath: sql:/etc/pki/nssdb
>  *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
>    CApath: none
>  * NSS error -12188
>  * Closing connection #0
>  * SSL connect error

## Error
curl: (35) SSL connect error

In the shim script it is also not running correctly. 

>   curl -vv -f${SELFSIGNED}Ss https://$static_host/shim.py 
>  * About to connect() to static.userify.com port 443 (#0)
>  *   Trying 104.20.15.168... connected
>  * Connected to static.userify.com (104.20.15.168) port 443 (#0)
>  * Initializing NSS with certpath: sql:/etc/pki/nssdb
>  *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
>    CApath: none
>  * NSS error -12188
>  * Closing connection #0
>   * SSL connect error

 curl --version
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz 

I fixed the install by add `-1` force TLS.

>  curl -v -1 -sS "https://static.userify.com/installer.sh" |     api_key="jNNGyRNkeLVL2TFjJs8FucD5CoAAX8284EFmrLM2RgYgwcaxR6"     api_id="4vDX5uRZXdZM887CEWXgQc_user"     static_host="static.userify.com"     shim_host="configure.userify.com"     self_signed=0     sudo -sE
>  * About to connect() to static.userify.com port 443 (#0)
>  *   Trying 104.20.15.168... connected
>  * Connected to static.userify.com (104.20.15.168) port 443 (#0)
>  * Initializing NSS with certpath: sql:/etc/pki/nssdb
>  *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
>    CApath: none
>  * SSL connection using TLS_RSA_WITH_AES_128_GCM_SHA256
>  * Server certificate:
>  * 	subject: CN=ssl369667.cloudflaressl.com,OU=PositiveSSL Multi-Domain,OU=Domain Control Validated
>  * 	start date: Mar 30 00:00:00 2016 GMT
>  * 	expire date: Oct 02 23:59:59 2016 GMT
>  * 	common name: ssl369667.cloudflaressl.com
>  * 	issuer: CN=COMODO RSA Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
> GET /installer.sh HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: static.userify.com
> Accept: */*
> 
>  < HTTP/1.1 200 OK
>  < Server: cloudflare-nginx
>  < Date: Wed, 06 Apr 2016 09:51:52 GMT
>  < Content-Type: application/octet-stream
>  < Content-Length: 10185
>  < Connection: keep-alive
>  < Set-Cookie: __cfduid=d6614791bdd559f0016321dab061a86341459936311; expires=Thu, 06-Apr-17 09:51:51 GMT; path=/; domain=.userify.com; HttpOnly
>  < Last-Modified: Mon, 04 Apr 2016 02:38:38 GMT
>  < ETag: "5701d3ae-27c9"
>  < Strict-Transport-Security: max-age=0; includeSubDomains; preload
>  < Accept-Ranges: bytes
>  < X-Content-Type-Options: nosniff
>  < CF-RAY: 28f457fb327515ec-JNB
>  < 
>  { [data not shown]
>  * Connection #0 to host static.userify.com left intact
>  * Closing connection #0

**Comment by jamiesonbecker** [comment]
Thanks for this issue -- AND the resolution! :)

We'll push this to cloud prod shortly!

**Comment by jamiesonbecker** [comment]
Awesome, completely fixed it -- thanks Aaron! Also added -1 to all of our curl's in the user interface etc.

The fix has been deployed to all production systems.
