### ISSUE TITLE
FreeBSD and OSX support

### ISSUE THREAD

**Issue by jamieson99** [userify/shim#28]
I started taking a look at getting this working on FreeBSD. Needs Python, curl, and bash installed, which the new FreeBSD 10.3 AMI's (huge thx to Colin Percival for his years-long effort on FreeBSD at AWS) do not have installed by default, but they're just a pkg install away. The upcoming check in installer for curl vs wget (https://github.com/userify/shim/issues/27) would resolve the curl dep.

Once that's done and a few minor hacks for things like /bin/bash relocation, the shim successfully pulls the JSON, but then has problems parsing /etc/passwd. A cursory review doesn't review any obvious issues, so that'll have to wait until later.

After that, there'll probably be the regular fixes and patches for inline sed (not easily available on *BSD since it's not POSIX), possibly adjusting useradd etc switches for creating new user accounts, adjusting for relocated /home (although it looks like it might 'just work'), and starting on reboot.

**Comment by jamiesonbecker** [comment]
Customer request: Adding FreeBSD support would be really great for CI/CD running on Mac (let's say you have a IOS app or a Mac app that you have a continuous integration/delivery pipeline set up for.) This definitely seems like a common scenario for software companies.

**Comment by jamiesonbecker** [comment]
Another use case that we've heard from for customers is to manage _private_ keys on OSX laptops, but that would definitely be a slightly different tool from the shim (although it might share some code).

**Comment by userifydevteam** [comment]
Consolidating this into #53
