### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jamieson99** [userify/shim#29]
Windows Server is getting a new Powershell-backed OpenSSH implementation. This is a placeholder issue for supporting it. (It'll be particularly awesome with Userify Enterprise's new Active Directory integration, which synchronizes with AD when available but doesn't need AD running to operate!)

Userify Enterprise (the server itself, not the shim) is probably not too far off from running on Windows as well... that'd be an interesting setup.

**Comment by userifydevteam** [comment]
Consolidating this into #53
