### ISSUE TITLE
RHEL6/CentOS6 and SELinux=enforcing needs security context restored

### ISSUE THREAD

**Issue by jamieson99** [userify/shim#30]
Thanks to the platform team at Gannett (esp Brian Lieberman and Rob Gindes) for tracking this down, providing a fix, and for testing the fix on RHEL7/CentOS7 and selinux=permissive. (This was primarily tested with CentOS, but the issue and fix are presumably also relevant to RHEL)

SELinux=enforcing is not the default for CentOS6 at AWS and this apparently doesn't pop up as an issue in 7, but after the user is added, the security context needs to be restored in 6 in order to accept the authorized_keys.

```
restorecon -Rv /home/$USER/.ssh
```

This should probably be (after a check to make sure restorecon exists) after the authorized_keys is created, somewhere around here: https://github.com/userify/shim/blob/master/shim.py#L238

Perhaps:
        # add quiet flag to qexec
        qexec(["restorecon", "-Rv", "/home/$USER/.ssh"], quiet=True)

Please comment if this affects you.

**Comment by brianlieberman** [comment]
👍

**Comment by ronlipke** [comment]
👍

**Comment by userifydevteam** [comment]
We don't believe this is an issue any more. Please re-open if so. Thank you!
