### ISSUE TITLE
No license file/notice?

### ISSUE THREAD

**Issue by e12e** [userify/shim#4]
Hi,

apologies if I missed it -- but I can't seem to find any license information on the python shim? I see it's marked as copyright, but can't find any explicit grant for use/redistribution etc? I'm guessing it's probably intended to be under BSD/MIT license?

**Comment by jamiesonbecker** [comment]
Hi e12e,

Thanks for asking :) the core shim is not open source, but as a matter of transparency and trust, we wanted to make it publicly visible on Github. (I personally like to see what anything I install is about to do to my system -- and, shoot, we're not going to be chasing down our customers if you do something cool with it internally -- in fact, we'd love to mix it in if you do something great and want to share!)

We're also adding extension capabilities -- those extensions can be released under whatever license the author(s) deem fit. (they might be commercial, open source, etc).

Kind regards,
Jamieson

**Comment by jamiesonbecker** [comment]
Leaving this issue open to add a proper LICENSE file.

**Comment by jamiesonbecker** [comment]
Resolved.
