### ISSUE TITLE
Shim updating non-userify users with same username

### ISSUE THREAD

**Issue by cthurbson** [userify/shim#40]
A user reported that the shim is modifying users (updating authorized_keys and sudoers) with the same username (as you might expect), but not removing them (as you also might expect).

It appears that this is due to current_userify_users() only within the removal loop. This check should be done probably here (https://github.com/userify/shim/blob/master/shim.py#L432) as well, or at each step, or make it possible to opt-in or out at the server configuration level.

https://github.com/userify/shim/blob/master/shim.py#L446

**Comment by jamiesonbecker** [comment]
Credit to Dileep Pothanchery for flagging this issue - thank you!

**Comment by dileep-p** [comment]
Really quick @jamiesonbecker 👍

**Comment by jamiesonbecker** [comment]
@dileep-p thanks! Further testing.. it wasn't quite right before in some corner cases. We need to do some more testing but planning to push an emergency build tonight if you have auto-updates enabled. Thanks again for the awesome bug report.
