### ISSUE TITLE
sudoers not getting removed, only added.

### ISSUE THREAD

**Issue by jamiesonbecker** [userify/shim#44]
Appears to be on https://github.com/userify/shim/blob/master/shim.py#L225

**Comment by jamiesonbecker** [comment]
Thanks to Craig and Sean at PLT for catching this.

**Comment by cthurbson** [comment]
Reproduced and confirmed, working on fix.

**Comment by jamiesonbecker** [comment]
This is a security bug, even if it's small, since reducing from root to 
user should always actually do it.

Seems like it's worthy of bug bounty. Agree?

**Comment by cthurbson** [comment]
Yes.

**Comment by jamiesonbecker** [comment]
Awesome! Minimal impact, so let's wrap it in.

**Comment by jamiesonbecker** [comment]
This is probably a very low impact bug, but let's plan on pushing tonight anyway. Fire drills are always fun;)
