### ISSUE TITLE
logging to tty0

### ISSUE THREAD

**Issue by claytondukes** [userify/shim#51]
Would you guys consider not logging to tty0? this is a major annoyance when a vm or cloud instance loses connectivity. I can't edit files or do anything without having:

```
rc.local[466]: curl: (6) Could not resolve host: static.userify.com
rc.local[466]: curl: (6) Could not resolve host: static.userify.com
```

Spamming the console every second.

It's driving me insane. This is especially brutal in cloud config setups since tty0 is used as the actual console.

The only thing I can do is uninstall userify, then I have to install again later.

**Comment by jamiesonbecker** [comment]
Hi Clayton,

Sorry about that! We just log to stdout, so it must be that your distribution is sending stdout to tty0  -- have you tried running the installer but directing output to /dev/null?

For example,

`curl .... | sudo -sE  >/dev/null 2>&1`

**Comment by claytondukes** [comment]
All instances do it. whether cloud-init or just straight os.
It's not the install doing it, it's when a vm/instance comes up with no network. (after userify is installed).
Maybe it's from the `/etc/rc.local` entry:

```
/opt/userify/shim.sh &
```

**Comment by jamiesonbecker** [comment]
We haven't been able to reproduce.

Can you clarify a bit when this happens? Are you're saying that you're pre-installing the userify installation into the image, and that if the instance comes up with no network and you're logged into it locally (or through a virtual KVM), that it's spamming you with messages that it can't get to the network.

>  Maybe it's from the /etc/rc.local entry

That seems like a reasonable guess. If you're pre-installing it, could you just add the `>/dev/null 2>&1` to the `/etc/rc.local` entry?

**Comment by jlyonsmith** [comment]
Yes, @jamiesonbecker we would love for you to add this to the installer. We hit this problem A LOT.  Often, we'll set up a machine up outside the data center with one set of network config, then install it on site and need to log into re-configure the network.  This message appears and makes it VERY VERY difficult to login into the system as it interferes with the user/password prompts on Ubuntu.

**Comment by jamiesonbecker** [comment]
@jlyonsmith Can you provide more information? Is this an actual hardware PC, and is it just the default install? Does it always log to the first console (tty0/pty0)?

**Comment by jlyonsmith** [comment]
@jamiesonbecker Yes its actual h/w.  Our site runs on around two dozen Dell blades across two data centers. We run ProxMox as our virtualization software and this problem hits on the VM's too.  We use the default install of Userify, pasting the curl command into the CLI.  We primarily get this problem when connecting to a machine using a crash cart (monitor & keyboard) to the systems in the event of a system failure, which often can be a network outage.  The spamming continues as long as the network is unavailable as shim.sh keeps forking new bash sessions even if you manage to successfully log in.  Just get an old PC and install Ubuntu on it, Userify it, unplug the network and reboot.  It's a super fun game trying to type a 16 character root password fast enough before the next curl error pops up!  ;)  The redirection trick above sadly does not solve the problem.

**Comment by jamiesonbecker** [comment]
Ouch ;) Thanks, this repro method is really helpful, especially the bit about the spamming only becoming an issue when there's no network! I'll have a look shortly.

**Comment by jamiesonbecker** [comment]
We'll deploy this to Cloud and on-prem editions after some more review. Thanks again @claytondukes for originally reporting this and to @jlyonsmith for the extra info.

**Comment by jamiesonbecker** [comment]
This patch was deployed to Userify Cloud today and will be deployed to on-prem over the weekend unless issues arise. Please update this issue once you've tested it (available now if you're using Userify Cloud), thanks again @jlyonsmith and @claytondukes

**Comment by jlyonsmith** [comment]
Wow!  Super speedy.  Thank you @jamiesonbecker !
