### ISSUE TITLE
Available shell list doesn't include zsh

### ISSUE THREAD

**Issue by jamiesonbecker** [userify/shim#6]
The shim should check for shell availability before user creation and then the list could include unusual shells. The shell selection list is a good start in this direction but currently only includes very common shells. (If your chosen shell isn't available on a given instance, you won't be able to log in. A fallback list would be ideal.)

This would allow using shells not installed by default such as /bin/zsh while sensibly falling back to /bin/bash or /bin/sh if not available.

Caveats:
This would probably require a pre-defined list of fallback shells, probably user's preferred shell first, /bin/bash if available, /bin/ash, /bin/sh, or first 'sh' shell in /etc/shells. Is /etc/shells POSIX standard and does it exist on *bsd?

**Comment by jamiesonbecker** [comment]
Shells that people might prefer (use color coding to show recommendations for newbies) in no particular order:

== Already available in userify:

     /bin/sh
     /bin/bash
     /bin/false
     /bin/nologin

== Should be added:

     /usr/bin/tmux
     /usr/bin/screen
     /bin/zsh
     /bin/dash
     /bin/ash
     /bin/rbash
     /bin/csh
     /bin/tcsh
     /bin/ksh

Any others (*bsd, solaris, etc)?

**Comment by jamiesonbecker** [comment]
This would require some sort of fallback logic in case the preferred shell isn't available. If anyone cares about this bug, please reopen or comment.

**Comment by adam-6over6** [comment]
Is there any update regarding this?
You can just check if the path to the preferred shell exists, and if not, default to /bin/bash

**Comment by jamiesonbecker** [comment]
Hi @adam-6over6, actually it was just that no one asked for this. It was part of the original feature wishlist for Userify. We'll put it back on the list!-- thanks for your comment!

**Comment by adam-6over6** [comment]
Thanks a bunch!

Best Regards,

Adam Gold | DevOps Manager
Mobile +972-503-045-135

**Comment by userifydevteam** [comment]
This feature has been completed and will be released in the next minor release of Userify 4, scheduled for the next week.

**Comment by userifydevteam** [comment]
This feature has been released to all editions! On Userify Cloud, it's immediately available. Userify Enterprise, Express, and AWS upgrade channels will receive the new release shortly. (Depending on your edition, you may need to force the upgrade by restarting your server.)

![image](https://user-images.githubusercontent.com/37945046/63451914-5d8cd480-c402-11e9-9091-876b0681fd16.png)

Thanks @adam-6over6 for helping bring this feature to fruition!
