### ISSUE TITLE
Ubuntu install flaky

### ISSUE THREAD

**Issue by pfordahl** [userify/shim#8]
Ubuntu: 14.04.1
Bug:
1st ran: After the shim is installed,the log file is not created as well as the home directories are not created. But it said it installed fine.
2nd run: everything installed fine.

**Comment by jamiesonbecker** [comment]
Your log file indicates a lot of spurious output. I'm trying to figure out why that's showing up, too. Maybe the bash on that system turns on set/shopts. 

https://github.com/userify/shim/blob/master/installer.sh#L22

There appears to be a bug there 2> should be >.

**Comment by pfordahl** [comment]
Just ran the shim again and it looks great!

**Comment by jamiesonbecker** [comment]
Excellent! Closing for now, but pls reopen if it pops up again. The next rev of the shim will have more comprehensive logging too.
