### ISSUE TITLE
Questions about different usage scenarios

### ISSUE THREAD

**Issue by michallipka** [userify/shim#9]
Hello,
I have single account (everyone) that everyone is allowed to login (of course if I add proper key to authorized_keys file).
1. Is managing this possible with userify? (I assign users to server and their public keys are added to ~everyone/.ssh/authorized_keys file or better some other file which user everyone is not allowed to edit - to prevent users from adding their own keys).
2. Is userify able to force specific set of public keys (if someone add something outside of userify this key will be removed on next run)?

**Comment by jamiesonbecker** [comment]
Sure, this is possible and thanks for using Userify!

1. Probably the easiest way to handle this would be to set up a single user account at Userify that everyone logs into and pastes their public key into (add a new line or two between keys just to be safe).

2. Sure! This will happen automatically - the authorized_keys on each user account are automatically rewritten if they don't match the server. (See https://github.com/userify/shim/blob/master/shim.py#L98 )

With that said :) Userify exists specifically to enable users to manage their own keys and their own accounts to maintain security and compliance with PCI, HIPAA, etc, so although possible we recommend that you just invite your users and use the visual capabilities of Userify to grant permissions to only the servers that they're invited to.

**Comment by michallipka** [comment]
I wasn't precise enough: is this possible with having separate user accounts at Userify (to easily manage who has access to server account "everyone")

**Comment by jamiesonbecker** [comment]
Ah, I see

**Comment by jamiesonbecker** [comment]
To fit the scenario that you describe, would it be possible for you to create and maintain the Userify user account for the `everyone` user as company admin, and Userify distributes the key?

**Comment by michallipka** [comment]
Probably this could work somehow. But I should distinguish keys somehow (with comments or so). I'd prefer to allow users to change their own keys (in case of creating new key or something) without bothering me :)

**Comment by jamiesonbecker** [comment]
Understood :) You can add comments to your keys, but the first one should start with ssh-rsa or ssh-dsa (that's how we check for obvious problems such as accidentally pasting in a private key)

ssh-rsa AAAA.... someuser@somewhere

# key2
ssh-rsa AAAA... someotheruser@somewhere

**Comment by jamiesonbecker** [comment]
Also, if you mess it up and fix it in the UI, your fixes will be pushed out almost immediately.

**Comment by michallipka** [comment]
but still I have to do it myself :)
maybe you should think about adding possibility to define server login for each pair userify_user/server (feature request ;)

**Comment by jamiesonbecker** [comment]
Let's dig into the scenario a bit deeper via email;  maybe some ideas that can work for you! (Enterprise@Userify.com) Thanks Michal!
